import anthropicProxyRoutesV2 from "./proxy/routesv2/anthropic";
import cerebrasProxyRoutesV2 from "./proxy/routesv2/cerebras";
import geminiProxyRoutesV2 from "./proxy/routesv2/gemini";
import ollamaProxyRoutesV2 from "./proxy/routesv2/ollama";
import openAiProxyRoutesV2 from "./proxy/routesv2/openai";
import vllmProxyRoutesV2 from "./proxy/routesv2/vllm";
import zhipuaiProxyRoutesV2 from "./proxy/routesv2/zhipuai";

export { default as a2aRoutes } from "./a2a";
export { default as agentToolRoutes } from "./agent-tool";
export { default as authRoutes } from "./auth";
export { default as autonomyPolicyRoutes } from "./autonomy-policies";
export { default as browserStreamRoutes } from "./browser-stream";
export { default as chatApiKeysRoutes } from "./chat/routes.api-keys";
export { default as chatRoutes } from "./chat/routes.chat";
export { default as chatModelsRoutes } from "./chat/routes.models";
export { default as dualLlmConfigRoutes } from "./dual-llm-config";
export { default as dualLlmResultRoutes } from "./dual-llm-result";
export { default as featuresRoutes } from "./features";
export { default as incomingEmailRoutes } from "./incoming-email";
export { default as interactionRoutes } from "./interaction";
export { default as internalMcpCatalogRoutes } from "./internal-mcp-catalog";
export { default as invitationRoutes } from "./invitation";
export { default as limitsRoutes } from "./limits";
export { default as llmProxyEntityRoutes } from "./llm-proxy-entity";
export { legacyMcpGatewayRoutes, newMcpGatewayRoutes } from "./mcp-gateway";
export { default as mcpGatewayEntityRoutes } from "./mcp-gateway-entity";
export { default as mcpServerRoutes } from "./mcp-server";
export { default as mcpServerInstallationRequestRoutes } from "./mcp-server-installation-requests";
export { default as mcpToolCallRoutes } from "./mcp-tool-call";
export { default as oauthRoutes } from "./oauth";
export { default as optimizationRuleRoutes } from "./optimization-rule";
export { default as organizationRoutes } from "./organization";
export { default as organizationRoleRoutes } from "./organization-role";
export { default as policyConfigSubagentRoutes } from "./policy-config-subagent";
export { default as promptAgentRoutes } from "./prompt-agents";
export { default as promptRoutes } from "./prompts";
// All proxy routes use the unified V2 handler
export const anthropicProxyRoutes = anthropicProxyRoutesV2;
export const cerebrasProxyRoutes = cerebrasProxyRoutesV2;
export const geminiProxyRoutes = geminiProxyRoutesV2;
export const openAiProxyRoutes = openAiProxyRoutesV2;
export const vllmProxyRoutes = vllmProxyRoutesV2;
export const ollamaProxyRoutes = ollamaProxyRoutesV2;
export const zhipuaiProxyRoutes = zhipuaiProxyRoutesV2;
export { default as secretsRoutes } from "./secrets";
export { default as statisticsRoutes } from "./statistics";
export { default as teamRoutes } from "./team";
export { default as tokenRoutes } from "./token";
export { default as tokenPriceRoutes } from "./token-price";
export { default as toolRoutes } from "./tool";
export { default as userRoutes } from "./user";
export { default as userTokenRoutes } from "./user-token";
